### ISSUE TITLE
Review folders structure

### ISSUE THREAD

**Issue by AnthonyPierrat** [AnthonyPierrat/typed-structures#12]
We need to structure our application.

I suggest 

- typed-structures/collections with all the different data structures
- typed-structures/algorithms 
- typed-structures/algorithms/sorts
- typed-structures/algorithms/searches
- typed-structures/tsQ

@ThibaudREY could you please give your opinion about this by commenting below ?

**I will implement the folders structure.**

**Comment by ThibaudREY** [comment]
I don't see why we need algorithms directories though, as the search and sort logic are all present int the classes themselves so far. Except if we plan to add some sort of search/sort algorithms regardless the class type we are processing. Sounds like a good idea actually, it will allow us to select more than a single structure in TsQ  and start to handle joins more efficiently than just passing a callback in the where clause.
Maybe we should also split the interface tree from the implementations as we will add more than one implementation for a single interface.
